# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moringaawardz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='editor',
            new_name='poster',
        ),
    ]
